# Generated by Django 4.0.3 on 2023-02-26 12:32

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='party',
            field=models.CharField(choices=[('party1', 'Party1'), ('party2', 'Party2'), ('party3', 'Party3')], default=None, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=200, unique=True)),
                ('approvals', models.ManyToManyField(blank=True, related_name='member_approvals', to=settings.AUTH_USER_MODEL)),
                ('disapprovals', models.ManyToManyField(blank=True, related_name='member_disapprovals', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='member_followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
