# Generated by Django 4.0.3 on 2023-02-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proposal_comment'),
        ('api', '0003_user_photo'),
    ]

    operations = [
    ]
