<<<<<<< HEAD
# Generated by Django 4.0.3 on 2023-02-26 15:48
=======
# Generated by Django 4.0.3 on 2023-02-26 17:12
>>>>>>> 3d4d9d21c0ad77377422247f8abe446e3b7f84ae

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proposal_comment'),
        ('api', '0003_user_photo'),
    ]

    operations = [
    ]
