# Generated by Django 4.0.3 on 2023-02-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_member_is_active_member_member_parliament_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='parliament_house',
            field=models.CharField(choices=[(1, 'Lords House'), (2, 'Commons House')], default=None, max_length=30, null=True),
        ),
    ]
