# Generated by Django 4.0.3 on 2023-02-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_member_parliament_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
