# Generated by Django 4.0.3 on 2023-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='parliament_house',
            field=models.CharField(choices=[('Lords House', 1), ('Commons House', 2)], default=None, max_length=30, null=True),
        ),
    ]
