# Generated by Django 4.0.3 on 2023-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_member_parliament_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='parliament_house',
            field=models.CharField(choices=[(1, 'Lords House'), (2, 'Commons House')], default=None, max_length=30, null=True),
        ),
    ]
