# Generated by Django 4.0.3 on 2023-02-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_member_parliament_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='public_id',
        ),
    ]
