# Generated by Django 4.0.3 on 2023-02-26 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_member_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='approvals',
            field=models.ManyToManyField(blank=True, related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='disapprovals',
            field=models.ManyToManyField(blank=True, related_name='disapprovals', to=settings.AUTH_USER_MODEL),
        ),
    ]
